const path = require('node:path');
const { pathToFileURL } = require('node:url');
const root = path.resolve(__dirname, '../..');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH || undefined,headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1536,height:1150},deviceScaleFactor:1});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const remote=[];page.on('request',r=>{if(/^https?:/.test(r.url()))remote.push(r.url())});
await page.goto(pathToFileURL(path.join(root, 'artifacts/nuget-map-demo.html')).href);
await page.screenshot({path:path.join(root, 'artifacts/report-desktop.png'),fullPage:true,animations:'disabled'});
const assert=(value,message)=>{if(!value)throw new Error(message)};
assert(await page.locator('.graph-node').count()>3,'graph rendered');
const reportName=await page.locator('#report-name').innerText();
assert(reportName==='Northstar Commerce','custom report title');
assert(await page.title()===reportName+' · NuGet Map','browser title matches report name');
assert(await page.locator('#sample-label').isVisible(),'demo label remains visible');
await page.locator('#packages-tab').click();
await page.locator('#search').fill('Newtonsoft');
assert(await page.locator('.list-item').count()===1,'package search');
await page.locator('.list-item').click();
assert((await page.locator('#inspector').innerText()).includes('Version drift detected'),'drift notice');
assert(await page.locator('.chain').count()>0,'dependency chains');
assert(await page.locator('#inspector [data-project]').count()===5,'reverse usage');
assert((await page.locator('.license-details').innerText()).includes('MIT'),'license expression in package inspector');
assert(await page.locator('.page-footer a').getAttribute('href')==='https://itperformance.dk','footer link');
assert((await page.locator('.page-footer').innerText()).includes('Powered by IT Performance'),'footer credit');
await page.locator('[data-view="inventory"]').click();
await page.locator('#license-filter').selectOption('unknown');
assert(await page.locator('#package-table tr').count()===1,'unknown license filter');
await page.locator('#license-filter').selectOption('acceptance');
assert((await page.locator('#package-table').innerText()).includes('FluentAssertions'),'acceptance metadata filter');
await page.locator('#package-table [data-package]').first().click();
assert((await page.locator('.license-details').innerText()).includes('LICENSE.txt'),'license file metadata');
await page.locator('[data-view="inventory"]').click();
await page.locator('#license-filter').selectOption('all');
await page.locator('[data-view="drift"]').click();
assert(await page.locator('#package-table tr').count()===4,'drift table');
await page.locator('#table-search').fill('no-such-package');
assert(await page.locator('#table-empty').isVisible(),'empty search state');
await page.locator('#table-search').fill('');
await page.locator('#package-table [data-package]').first().click();
assert(await page.locator('#map-view').isVisible(),'table inspect navigation');
await page.locator('#depth').selectOption('1');
const direct=await page.locator('.graph-node').count();
await page.locator('#depth').selectOption('99');
assert(await page.locator('.graph-node').count()>direct,'depth control');
const before=await page.locator('#viewport').getAttribute('transform');
await page.locator('#zoom-in').click();
assert(await page.locator('#viewport').getAttribute('transform')!==before,'zoom works');
const downloadPromise=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadPromise;assert(download.suggestedFilename()==='nuget-map.json','JSON export');
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:path.join(root, 'artifacts/report-mobile.png'),fullPage:true,animations:'disabled'});
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'no horizontal mobile overflow');
assert(errors.length===0,'browser errors: '+errors.join(','));assert(remote.length===0,'unexpected network requests');
console.log('PASS browser: graph, search, reverse usage, chains, licenses, license filters, footer, drift table, empty state, navigation, depth, zoom, JSON export, responsive layout, offline resources.');
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
